language: python
python:
- '2.7'
install:
- pip install -r requirements.txt
before_script:
- . scripts/autocomplete_obole
- obole create_project_structure
- obole create_db_passwords
- obole create_db
script:
- python manage.py test --noinput --failfast users objects groups transactions
notifications:
  email: false
  slack: voilier:ltkboXjosDG1PMIIHKGcpQl2
