language: python
python:
- '2.7'
services:
- postgresql
install:
- pip install -r requirements.txt
before_script:
- . scripts/autocomplete_obole
- ./scripts/obole create_project_structure
- ./scripts/obole create_db_passwords
- ./scripts/obole create_db
- ./scripts/obole migrate
script:
- ./scripts/obole test
notifications:
  email: false
  slack: voilier:ltkboXjosDG1PMIIHKGcpQl2
after_success:
  - bash <(curl -s https://codecov.io/bash)
