language: python
python:
- '2.7'
install:
- pip install -r requirements.txt
script:
- python manage.py test --noinput --failfast users objects groups transactions
notifications:
  email: false
  slack: voilier:ltkboXjosDG1PMIIHKGcpQl2
