# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-25 13:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('groups', '0001_initial'),
        ('users', '0001_initial'),
        ('objects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.PositiveSmallIntegerField(choices=[(0, 'Gift'), (1, 'Lend'), (2, 'Exchange')])),
                ('visibility1', models.PositiveSmallIntegerField(choices=[(0, 'Just me'), (1, 'Partner'), (2, 'Friends'), (3, 'Friends & their friends'), (4, 'Public'), (5, 'Custom')])),
                ('visibility2', models.PositiveSmallIntegerField(choices=[(0, 'Just me'), (1, 'Partner'), (2, 'Friends'), (3, 'Friends & their friends'), (4, 'Public'), (5, 'Custom')])),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groups.Group')),
                ('object1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transacted_from', to='objects.Object')),
                ('object2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transacted_to', to='objects.Object')),
                ('user1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions_initiated', to='users.User')),
                ('user2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions_received', to='users.User')),
            ],
        ),
    ]
