# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-26 14:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='objectcustomvisibility',
            old_name='obj',
            new_name='object',
        ),
        migrations.AlterField(
            model_name='objectpermissions',
            name='permission',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Can be lent before being returned')]),
        ),
    ]
