#!/bin/bash

set_for_production() {
  ENV=prod
  ROOT_DIR=/webapps/obole
  PROJECT_DIR="${ROOT_DIR}/sources"
  VENV_DIR="${ROOT_DIR}/virtualenv"
  ENV_COLOR='\033[1;31m'
}

set_for_ci() {
  ENV=ci
  ROOT_DIR=/webapps/obole
  PROJECT_DIR="${ROOT_DIR}/sources"
  VENV_DIR="${ROOT_DIR}/virtualenv"
  ENV_COLOR='\033[1;33m'
}

set_for_gitlab_ci() {
  ENV=gitlabci
  ROOT_DIR="$(cd "$(dirname "$0")"/..; pwd)"
  PROJECT_DIR="${ROOT_DIR}"
  VENV_DIR="${PROJECT_DIR}/virtualenv"
  ENV_COLOR='\033[1;35m'
}

set_for_development() {
  ENV=dev
  ROOT_DIR="$(cd "$(dirname "$0")"/..; pwd)"
  PROJECT_DIR="${ROOT_DIR}"
  VENV_DIR="${WORKON_HOME:-~/.virtualenvs}/obole"
  ENV_COLOR='\033[1;34m'
}

line() {
  local cols=$(tput cols 2>/dev/null)
  yes "$1" | head -n${cols:-80} | tr -d '\n'; echo
}

print_configuration() {
  line _
  echo
  echo -e "    \033[1;37mEnvironment:  ${ENV_COLOR}${ENV}\033[0m"
  echo
  echo    "       Root dir:  $ROOT_DIR"
  echo    "    Project dir:  $PROJECT_DIR"
  echo    " Virtualenv dir:  $VENV_DIR"
  line _
  echo
}

main() {
  case "$HOSTNAME" in
    'obole-ci') set_for_ci ;;
    'obole') set_for_production ;;
    *) set_for_development ;;
  esac

  case "$1" in
    get_project_dir) echo "${PROJECT_DIR}"; exit 0 ;;
  esac

  export ENV ROOT_DIR PROJECT_DIR VENV_DIR HOSTNAME
  print_configuration
  trap exit SIGINT

  command_name="$1"
  command="${PROJECT_DIR}/scripts/commands-${ENV}/$command_name"
  shift

  if [ -f "$command" ]; then
    if [ -x "$command" ]; then
      "$command" "$@"
      exit $?
    else
      echo "$command_name is not executable, give it a chmod +x" >&2
      exit 3
    fi
  else
    if [ -f "${PROJECT_DIR}/scripts/commands/$command_name" ]; then
      echo "$command_name is unauthorized or irrelevant in this environment" >&2
      exit 2
    else
    . "${VENV_DIR}/bin/activate"
      "${PROJECT_DIR}/manage.py" "$command_name" "$@"
    fi
  fi
}

main "$@"
