#!/bin/bash

init() {
  grep -q 'deb http://apt\.postgresql\.org/pub/repos/apt trusty-pgdg main' /etc/apt/sources.list.d/pgdg.list && return 0
  sudo bash -c "echo deb http://apt.postgresql.org/pub/repos/apt trusty-pgdg main > /etc/apt/sources.list.d/pgdg.list"
  wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo apt-key add -
  sudo apt-get update
}

init
cd "${PROJECT_DIR}/scripts/data/dependencies"
sudo apt-get install -y $(cat "apt")
sudo apt-get install -y $(cat "apt_${ENV}")
sudo npm update -g npm
sudo npm install -g $(cat "npm") $(cat "npm_${ENV}")
sudo -H pip install -U pip
sudo -H pip install virtualenv

sudo service postgresql restart
